<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>compute commissions</name>
  <uuid>f4ca7f80-3928-4a31-afec-a6c86c42f852</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
set tier to a tier in Tiers ;   
set min to the min of tier * Quota ;
set max to the max of tier * Quota ;
set rate to the rate of tier;

if  Revenue is more than max 
then
    set decision to decision + (max - min) * rate;
    print  " Tier:" + min + "/"+ max + " rate:" + rate*100 + "% Comm:" + ((max-min) * rate);
else 
    set decision to decision + (Revenue - min) * rate;
    print  "Tier:" + min + "/"+ max + " rate:" + rate*100 + "% out of " + (Revenue - min) + " Comm:" + ((Revenue - min) * rate);
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
