<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>initialize</name>
  <uuid>2326b0de-3305-46a8-9526-531419c9ce20</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0 ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
