<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>EW Advice rule</name>
  <uuid>4a566b83-f7db-4bd9-8801-bbf41513c3eb</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Name is defined 
then
	set decision to "Hello " + Name + "! " + 'Weather advice' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
