<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>a71b50e1-f0b0-43cf-8cc0-659a8381c3a5</uuid>
  <documentation><![CDATA[output the incentives value]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'New account bonus' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
