<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Compute recognized revenue</name>
  <uuid>04e099cb-ac78-4dd9-991e-7e3afb8bcd6e</uuid>
  <documentation><![CDATA[Determine the amount of recognized revenue]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the amount * 'Recognized revenue rate' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
