<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>commissions</name>
  <uuid>c27d9945-e8a1-4622-a32a-60953537db8d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'Commisions on transactions' + Incentives  ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
