<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>5a5296f2-ad44-490a-8677-6b46d2a8d29a</uuid>
  <documentation><![CDATA[Set the default value for commissions]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
