<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Revenue commissions</name>
  <uuid>318e9300-5d4e-4d0a-9700-8c01853d795e</uuid>
  <documentation><![CDATA[Determine the revenue commissions]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[if 'Commission method' is Revenue commissions
then
    set decision to the revenue commissions computed from 
    Revenue being Revenue , 
    Quota being Quota ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
