<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>cc2abdeb-3bdd-4158-bbf2-15716f2ea3cd</uuid>
  <documentation><![CDATA[Set the default value for the revenue]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
